### ISSUE TITLE
使用的QQ版本需要更新

### ISSUE THREAD

**Issue by Fwindy** [TimeRainStarSky/Yunzai-Lagrange-Plugin#4]
目前登录时会报错：
[10000000000] 登录错误：[安全提醒]你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。(140022017)
发送 #Bot上线10000000000 重新登录

在6月21日之前都是正常使用的，6月21日之后才开始报错。更换过签名地址，并且确认签名地址有效，但还是报错。

**Comment by Fwindy** [comment]
改成使用Lagrange.OneBot了，可以正常使用

**Comment by daqyt** [comment]
问一下，你登录多少个QQ

**Comment by 1545043459** [comment]
问一下，你登录多少个QQ
